config/routes.rb
Rails.application.routes.draw do
  

  namespace :dashboard do
    namespace :admin do
      get 'subjects/index'
    end
  end

  namespace :dashboard do
    namespace :admin do
      get 'subjects/show'
    end
  end

  namespace :dashboard do
    namespace :admin do
      get 'subjects/new'
    end
  end

  namespace :dashboard do
    namespace :admin do
      get 'subjects/edit'
    end
  end

  namespace :dashboard do
    namespace :admin do
      get 'subjects/delete'
    end
  end

  namespace :dashboard do
    namespace :teacher do
      get 'subjects/index'
    end
  end

  namespace :dashboard do
    namespace :teacher do
      get 'subjects/show'
    end
  end

  namespace :dashboard do
    namespace :teacher do
      get 'subjects/new'
    end
  end

  namespace :dashboard do
    namespace :teacher do
      get 'subjects/edit'
    end
  end

  devise_for :students
  devise_for :teachers
  devise_for :admins

  namespace :dashboard do
   authenticated :student do 
      resources :subjects, module: "student", :only=> [:show, :index]
    end

    authenticated :teacher do
      resources :subjects, module: "teacher"
    end

    authenticated :admin do
      resources :subjects, module: "admin"
    end
    root to: "dashboard#index"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html



  get 'pages/index'
  
  root to: "pages#index"
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < User
end

app/models/teacher.rb
class Teacher < User
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    devise_group :user, contains: [:student, :teacher, :admin]

    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    private
        def configure_permitted_parameters
          added_attrs = [:email, :password, :password_confirmation, :remember_me, :name]
          devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
          devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        end
end

app/controllers/dashboard/admin/subjects_controller.rb
class Dashboard::Admin::SubjectsController < ApplicationController
    before_action :authenticate_admin!

    def index
    
    end


    def show
    
    end

    def new

    end

    def delete

    end

    def edit

    end
end

app/controllers/dashboard/dashboard_controller.rb
class Dashboard::DashboardController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/dashboard/student/subjects_controller.rb
class Dashboard::Student::SubjectsController < ApplicationController
        before_action :authenticate_student!

        def index
        
        end

        def show
        
        end
end

app/controllers/dashboard/teacher/subjects_controller.rb
class Dashboard::Teacher::SubjectsController < ApplicationController
    before_action :authenticate_teacher!

    def index
        @users
    end


    def show
    
    end

    def new

    end
    

    def edit

    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/dashboard_helper.rb
module Dashboard::DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/dashboard/dashboard/index.html.erb
<h1>Dashboard::Dashboard#index</h1>
<% if student_signed_in? %>
    <p>I'm a Student</p>
<% end %>

<% if teacher_signed_in? %>
    <p>I'm a Teacher</p>
<% end %>

<% if admin_signed_in? %>
    <p>I'm a Admin</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learneen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
   <div class= "container">
    <p class="alert"><%= alert %></p>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg  navbar navbar-dark sticky-top" style="background-color: #669999;">
  <a class="navbar-brand " href="/"><span class="mb-0 h1"> Learneen </span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto  my-2 my-lg-0 ">
      <li class="nav-item active">
        <a class="nav-link" href="/"><span class="mb-0 h5">Home </span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/"><span class="mb-0 h5">Features</span></a>
      </li>
      
        <li class="nav-item"> 
          <% if  student_signed_in? %>
            <span class="mb-0 h5">
              <%= link_to 'Sign out', destroy_student_session_path, method: :delete, class: 'nav-link' %>
            </span
          <% elsif teacher_signed_in? %>
            <span class="mb-0 h5">
              <%= link_to 'Sign out', destroy_teacher_session_path, method: :delete, class: 'nav-link' %>
            </span>
          <% elsif  admin_signed_in? %>
            <span class="mb-0 h5">
              <%= link_to 'Sign out', destroy_admin_session_path, method: :delete, class: 'nav-link' %>
            </span>
          <% else %>
            
            <li class="nav-item">
            <span class="mb-0 h5">
              <%= link_to 'Sign In', new_student_session_path, class:'nav-link' %>
            </span>
            </li>

            <li class="nav-item">
            <span class="mb-0 h5">
              <%= link_to 'Register', new_student_registration_path, class:'nav-link' %>
            </span>
            </li>
    
            
          <% end %>
        </li>
    </ul>
  </div>
</nav>